_wandb:
    value:
        cli_version: 0.21.0
        e:
            o5ih0gx3wse7h2b6t5dls1v7fvtd8w7r:
                args:
                    - --config
                    - configs/baseline_lstm.yaml
                    - --wandb
                codePath: src/drone_rl/train/train.py
                codePathLocal: src/drone_rl/train/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "490577010688"
                        used: "108900958208"
                email: dulcichm@andrews.edu
                executable: /home/mrdulcich/miniconda3/envs/drone-rl/bin/python
                git:
                    commit: 2c84a6a6046bc7e85093e443eb71645437e0ae30
                    remote: https://github.com/MatthewDulcich/DeepLearning612.git
                host: mrdulcich-SER
                memory:
                    total: "13513261056"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/mrdulcich/Desktop/DeepLearning612/src/drone_rl/train/train.py
                python: CPython 3.10.18
                root: /home/mrdulcich/Desktop/DeepLearning612
                startedAt: "2025-07-24T21:45:50.257336Z"
                writerId: o5ih0gx3wse7h2b6t5dls1v7fvtd8w7r
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
env_id:
    value: FlyCraft-v0
eval_freq:
    value: 1
n_envs:
    value: 1
output_dir:
    value: runs
policy:
    value: lstm
policy_kwargs:
    value:
        dropout: 0.1
        lstm_hidden: 256
        lstm_layers: 2
ppo_kwargs:
    value:
        batch_size: 64
        clip_range: 0.2
        gae_lambda: 0.95
        gamma: 0.995
        learning_rate: 0.0003
        n_epochs: 3
        n_steps: 1
run_name:
    value: baseline_lstm
save_freq:
    value: 1
seed:
    value: 11
timesteps:
    value: 10000
