# ─────────────────────────────────────────
#   Debug MLP Policy (Local Test)
# ─────────────────────────────────────────
env_id: FlyCraft-v0
run_name: debug_mlp_local
output_dir: runs
seed: 42

# ───────── Parallel rollout settings ─────────
n_envs: 2
max_episode_steps: 200

# ───────── MLP policy ─────────
policy: mlp
policy_kwargs:
  net_arch: [32, 32]

# ───────── PPO hyper-parameters ─────────
ppo_kwargs:
  learning_rate: 1e-3
  n_steps: 128
  batch_size: 16
  gamma: 0.98
  gae_lambda: 0.90
  clip_range: 0.3
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.3
  n_epochs: 2

# ───────── Training length ─────────
timesteps: 2000

# ───────── Logging / checkpoints ─────────
save_freq: 500
eval_freq: 500
n_eval_episodes: 2
