timesteps: 1000000
env_id: FlyCraft-v0
run_name: baseline_lstm
output_dir: runs
seed: 11
n_envs: 4

policy: lstm
policy_kwargs:
  lstm_hidden: 512
  lstm_layers: 2
  dropout: 0.2

ppo_kwargs:
  learning_rate: 1.0e-4
  n_steps: 256
  batch_size: 128
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.98
  ent_coef: 0.02
  vf_coef: 1.0
  clip_range: 0.2

timesteps: 1000000
save_freq: 20000
eval_freq: 10000
