# Minimal baseline LSTM config for quick offline retraining
timesteps: 10000           # Much fewer steps for quick runs
env_id: FlyCraft-v0
run_name: baseline_lstm_quick
output_dir: runs
seed: 11
n_envs: 1                  # Single environment for less resource usage

policy: lstm
policy_kwargs:
  lstm_hidden: 128         # Smaller LSTM
  lstm_layers: 1
  dropout: 0.1

ppo_kwargs:
  learning_rate: 3.0e-4    # Slightly higher for faster learning
  n_steps: 64              # Shorter rollouts
  batch_size: 32           # Smaller batch
  n_epochs: 4              # Fewer epochs per update
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0.01
  vf_coef: 0.5
  clip_range: 0.2

save_freq: 2000
eval_freq: 1000
