env_id: FlyCraft-v0
run_name: baseline_lstm
output_dir: runs
seed: 11
n_envs: 1

policy: lstm
policy_kwargs:
  lstm_hidden: 256
  lstm_layers: 2
  dropout: 0.1

ppo_kwargs:
  learning_rate: 3.0e-4
  n_steps: 128
  batch_size: 128
  n_epochs: 3
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.2

timesteps: 1000
save_freq: 50
eval_freq: 20
